language: java
jdk: oraclejdk11

# Cache the .m2 folder and .sonar to prevent downloading dependencies on each build
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

# Define the services to use
services:
  - docker

script:
  - mvn clean verify
