language: java
jdk: oraclejdk11

# Cache the .m2 folder and .sonar to prevent downloading dependencies on each build
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

# Define the services to use
services:
  - docker

script:
  - mvn clean verify
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  - docker build -t benjaminlegrosperso/application-students-test-db-changelog-job:latest sample-application-db-changelog-job
  - docker build -t benjaminlegrosperso/application-students-test-http-api-server:latest sample-application-http-api-server
  - docker push benjaminlegrosperso/application-students-test-db-changelog-job:latest
  - docker push benjaminlegrosperso/application-students-test-http-api-server:latest
